version = 0.1

[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "OuroborosAppSam"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-ze4ea4ny4jlm"
s3_prefix = "OuroborosAppSam"
region = "ap-southeast-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
disable_rollback = true
